name: Sync Check

on: pull_request

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if branch is in sync with main
        run: |
          # git checkout origin/test1
          git fetch origin main
          if git merge-base --is-ancestor main @
          then
            echo "Your branch is up to date."
            exit 0
          else
            echo "You need to merge / rebase."
            exit 1
          fi
