name: PR Sync Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  pr-sync-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is in sync with main
        run: |
          base_branch=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}" | jq -r .base.ref)
          git fetch origin $base_branch
          if git log origin/${base_branch}..HEAD | grep -q "Merge branch '${base_branch}' into"; then
            echo "PR is not in sync with ${base_branch}. Please rebase your branch."
            exit 1
          fi
