name: Up-to-Date Check

on:
  pull_request

jobs:
  up-to-date-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if PR is up to date with main
        run: |
          git branch
          git fetch origin main
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
            echo "PR is behind main. Please rebase your branch."
            exit 1
          fi
