name: PR Sync Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  pr-sync-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is in sync with main
        run: |
          if git merge-base --is-ancestor main @
          then
            echo "Your branch is up to date."
            exit 0
          else
            echo "You need to merge / rebase."
            exit 1
          fi
